### ISSUE TITLE
Icons in decoration is parsed as links

### ISSUE THREAD

**Issue by takker99** [progfay/scrapbox-parser#1147]
**Describe the bug**
Icons in decoration is parsed as links.
These should be parsed as icons.

For example:

`[scrapbox.icon]`
`[* [scrapbox.icon]]`
`[** [scrapbox.icon]]`
`[*** [scrapbox.icon]]`
`[- [scrapbox.icon]]`
`[* [[scrapbox.icon]]]`

[![Image from Gyazo](https://i.gyazo.com/a3f8745d8399449a05d8e97aad15764f.png)](https://gyazo.com/a3f8745d8399449a05d8e97aad15764f)

There seems no changes in icons surrounded by single `*` or other decorations, but parsed objects of them has difference from that of plain icons.

**To Reproduce**
Please see the wrong snapshot.
https://github.com/takker99/scrapbox-parser/commit/692cb4df6be0bb23cd41bc2d31036d2da6c76fb5

**Expected behavior**
Icon in decoration is parsed as icon

Note: I wrote the issue largely based on https://github.com/progfay/scrapbox-parser/issues/867#issue-1046485807

Thank you for maintaining!

**Comment by progfay** [comment]
@takker99 
Great works!
This fix ware merged and released in [`@progfay/scrapbox-parser@8.1.0`](https://www.npmjs.com/package/@progfay/scrapbox-parser/v/8.1.0) 🎉
