### ISSUE TITLE
Named capture groups is not implemented in Firefox

### ISSUE THREAD

**Issue by rokoucha** [progfay/scrapbox-parser#35]
# Describe the bug

In Firefox, Named capture groups are not implemented.

## To Reproduce

https://github.com/progfay/scrapbox-parser/blob/51f02ce070b7f33616d13241a6d4d03daefb5860/src/block/node/UrlNode/index.ts#L5-L8
This code will be throw `SyntaxError: invalid regexp group`.

## Expected behaviour

No error is thrown.

## Affected devices

https://caniuse.com/#feat=mdn-javascript_builtins_regexp_named_capture_groups

### Desktop

 - OS: any OS
 - Browser: Firefox
 - Version: all version

### Smartphone

 - OS: Android
 - Browser: Firefox
 - Version: all version

## Additional context

Babel plugin is provided.
https://babeljs.io/docs/en/babel-plugin-transform-named-capturing-groups-regex

**Comment by progfay** [comment]
Thanks for your bug report, @rokoucha !
In #36 ,add modern browser compatibilities with babel.
This PR will be merged to master branch, and new version packages will be released.

**Comment by progfay** [comment]
@rokoucha 
Now, [`@progfay/scrapbox-parser@4.0.0-1`](https://www.npmjs.com/package/@progfay/scrapbox-parser/v/4.0.0-1) is released!
Available UMD build from https://www.npmjs.com/package/@progfay/scrapbox-parser/v/4.0.0-1 .
Please try it.
