### ISSUE TITLE
Broken decoration with absolute link

### ISSUE THREAD

**Issue by e-jigsaw** [progfay/scrapbox-parser#4]
**Describe the bug**
Parse broken when decoration with absolute link.

**To Reproduce**
https://runkit.com/embed/by1o9ax6ugx4

**Expected behavior**
```
type: 'decoration'
nodes: [
  {...}
]
```

**Screenshots**
[![Screenshot from Gyazo](https://gyazo.com/c7c81f20209bea90dbee6f5d84e7f721/raw)](https://gyazo.com/c7c81f20209bea90dbee6f5d84e7f721)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Node.js
 - Version 10.16.3

**Comment by progfay** [comment]
@e-jigsaw I fix it, please check #6

**Comment by e-jigsaw** [comment]
thank you for blazing fast fixing!!
