### ISSUE TITLE
Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by e-jigsaw** [progfay/scrapbox-parser#667]
**Describe the bug**
Hi @progfay 

https://github.com/progfay/scrapbox-parser/blob/master/src/block/node/ExternalLinkNode.ts#L7 `(?<=^| )https?:\/\/[^[\s\]]+` is Node.js(latest v14) and Chrome(stable latest) can parse. But Safari 14 seems can not parse `(?<=^| )` section. So crash Safari users.

**To Reproduce**
<img width="1112" alt=" 2021-05-06 7 54 36" src="https://user-images.githubusercontent.com/557961/117219489-54df6a80-ae40-11eb-8aa1-681b8d6863ea.png">

**Expected behavior**
Is it possible some alternative expression for Safari?

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- Browser Safari
- Version 14

**Smartphone (please complete the following information):**

- Device: iPad Pro
- OS: iPadOS
- Browser Safari
- Version 14

**Additional context**

**Comment by e-jigsaw** [comment]
Safari does not support lookbehind expressions.... https://caniuse.com/?search=lookbehind :(

**Comment by progfay** [comment]
Thank you for your reporting!

This issue was solved in #669 and #670 to avoid to use lookbehind RegExp.

This changing was released at [@progfay/scrapbox-parser@7.1.0](https://www.npmjs.com/package/@progfay/scrapbox-parser/v/7.1.0).

**Comment by e-jigsaw** [comment]
thank you for blazing fast fix!!
