### ISSUE TITLE
[http://example.com http://example.com] => type: image

### ISSUE THREAD

**Issue by e-jigsaw** [progfay/scrapbox-parser#7]
**Describe the bug**
- `[http://example.com http://example.com]` parses `type: image`
- `[http://example.com foo]` parses `type: link`
- `[foo http://example.com]` parses `type: link`

why [url url] style parse to image... :(

**To Reproduce**
https://runkit.com/embed/mlc24uokjfas

**Expected behavior**
- `[http://example.com http://example.com]` parses `type: link`

**Screenshots**
[![Screenshot from Gyazo](https://gyazo.com/5d23d19be90219dd950fa9f25ce3758c/raw)](https://gyazo.com/5d23d19be90219dd950fa9f25ce3758c)

**Desktop (please complete the following information):**
- OS: macOS 10.14.6
- Browser Node.js
- Version 10.16.3

Thanks

**Comment by e-jigsaw** [comment]
@progfay ping

**Comment by progfay** [comment]
Sorry for being late.
I fix it, please check PR #8 .

**Comment by e-jigsaw** [comment]
haya!!

**Comment by progfay** [comment]
I published new version 2.2.0 now!
