### ISSUE TITLE
Hashtag in decoration is parsed as plain text

### ISSUE THREAD

**Issue by hata6502** [progfay/scrapbox-parser#867]
**Describe the bug**
Hashtag in decoration is parsed as plain text.
It should be parsed as hashtag.

```text
[+ #tag]
```

[![Image from Gyazo](https://i.gyazo.com/7e83277adfce87bb8989f6f1005ccaf7.png)](https://gyazo.com/7e83277adfce87bb8989f6f1005ccaf7)

**To Reproduce**
Please see the wrong snapshot.

https://github.com/hata6502/scrapbox-parser/commit/4213a2834f454ce28667b514ebc0c35e994ade6f

**Expected behavior**
Hashtag in decoration is parsed as hashtag.

Thank you for maintaining! :)

**Comment by hata6502** [comment]
hashTag is parsed in DecorationNode and StrongNode.
But it becomes plain text in Table.

```text
	DecorationNode
		[+ #tag]
	StrongNode
		[* #tag]
	Table
		table:table
			#tag

```

[![Image from Gyazo](https://i.gyazo.com/1cce5440f9c63abf11ac0577c46384ea.png)](https://gyazo.com/1cce5440f9c63abf11ac0577c46384ea)

**Comment by progfay** [comment]
Thanks, it's my mistake.
I seem that PR https://github.com/progfay/scrapbox-parser/pull/868 is reasonable changes.

So, why the PR was closed? > @hata6502

**Comment by hata6502** [comment]
Sorry!, but my pull request effects to Table block.

https://github.com/hata6502/scrapbox-parser/commit/235cce990857aacfdf8380e100cd15622965cdca

So, I think new flag (such as `parseOnTable`) is needed to resolve this problem.

**Comment by progfay** [comment]
Hmm... OK, I see.

I found another bug in the parsing result of table cells. (https://github.com/progfay/scrapbox-parser/issues/869)

The problem of parsing table cells should be considered separately from the main topic of https://github.com/progfay/scrapbox-parser/issues/867.
Let's solve the problem of parsing hashtags first.
